#MySQL database
spring.datasource.url=jdbc:mysql://localhost:3306/iot_shop
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
# Change this to your MySQL username
spring.datasource.username=your_urser_name
# Change this to your MySQL password
spring.datasource.password=your_urser_password
